collections:
    athletic-performance-training:
        output: true
        defaults:
            scope:
                path: ""
                type: "athletic-performance-training"
            values:
                layout: "post"
    camps-clinics-workshops:
        output: true
        defaults:
            scope:
                path: ""
                type: "camps-clinics-workshops"
            values:
                layout: "post"
    getting-started:
        output: true
        defaults:
            scope:
                path: ""
                type: "getting-started"
            values:
                layout: "post"
    crossfit:
        output: true
        defaults:
            scope:
                path: ""
                type: "crossfit"
            values:
                layout: "post"
    olympic-lifting:
        output: true
        defaults:
            scope:
                path: ""
                type: "olympic-lifting"
            values:
                layout: "post"        